export const AvabilityHours: { id: number; name: string }[] = [
    { id: 1, name: '8:00' },
    { id: 2, name: '9:00' },
    { id: 3, name: '10:00' },
    { id: 4, name: '11:00' },
    { id: 5, name: '12:00' },
    { id: 6, name: '13:00' },
    { id: 7, name: '14:00' },
    { id: 8, name: '15:00' },
    { id: 9, name: '16:00' },
    { id: 10, name: '17:00' },
    { id: 11, name: '18:00' },
    { id: 12, name: '19:00' },
    { id: 13, name: '20:00' },
    { id: 14, name: '21:00' },
    { id: 15, name: '22:00' },
  ];

  export const AvabilityDays: { id: number; name: string }[] = [
    { id: 1, name: 'Pon.' },
    { id: 2, name: 'Wt.' },
    { id: 3, name: 'Śr.' },
    { id: 4, name: 'Czw.' },
    { id: 5, name: 'Pt.' },
    { id: 6, name: 'Sob.' },
    { id: 7, name: 'Niedz.' },
  ];

  export const AvabilityHoursNames: { id: number; name: string }[] = [
    { id: 1, name: 'eight' },
    { id: 2, name: 'nine' },
    { id: 3, name: 'ten' },
    { id: 4, name: 'eleven' },
    { id: 5, name: 'twelve' },
    { id: 6, name: 'thirteen' },
    { id: 7, name: 'fourteen' },
    { id: 8, name: 'fifteen' },
    { id: 9, name: 'sixteen' },
    { id: 10, name: 'seventeen' },
    { id: 11, name: 'eighteen' },
    { id: 12, name: 'nineteen' },
    { id: 13, name: 'twenty' },
    { id: 14, name: 'twentyOne' },
    { id: 15, name: 'twentyTwo' },
  ];
